import type { Metadata } from "next";
import { Fira_Code, Architects_Daughter } from "next/font/google";
import localFont from "next/font/local";
import "../styles/globals.css";

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

const architectsDaughter = Architects_Daughter({
  variable: "--font-architects-daughter",
  subsets: ["latin"],
  weight: "400",
});

const georgia = localFont({
  src: [
    {
      path: "../../public/fonts/georgia/georgia.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-georgia",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.variable} ${architectsDaughter.variable} ${georgia.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
